cache: bundler
language: ruby
rvm:
  - 2.1.5
  - 2.1.4
  - 2.1.3
  - 2.1.2
  - 2.1.1
  - 2.0.0
  - 1.9.3
  - 1.9.2
  - 1.8.7

gemfile:
  - gemfiles/rails23Gemfile
  - gemfiles/rails30Gemfile
  - gemfiles/rails31Gemfile
  - gemfiles/rails32Gemfile
  - gemfiles/rails40Gemfile
  - gemfiles/rails41Gemfile
matrix:
  fast_finish: true
  exclude:
    - rvm: 1.8.7
      gemfile: Gemfile
    - rvm: 1.9.2
      gemfile: gemfiles/rails23Gemfile
    - rvm: 1.9.3
      gemfile: gemfiles/rails23Gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/rails23Gemfile
    - rvm: 2.1.1
      gemfile: gemfiles/rails23Gemfile
    - rvm: 2.1.2
      gemfile: gemfiles/rails23Gemfile
    - rvm: 2.1.3
      gemfile: gemfiles/rails23Gemfile
    - rvm: 2.1.4
      gemfile: gemfiles/rails23Gemfile
    - rvm: 2.1.5
      gemfile: gemfiles/rails23Gemfile
